Ismet
khicchi/BugPatrolMission1 pull request #6
Opened 2021-10-01 15:18 UTC by ismetgunes

Can you check my solution. After check, please send me a feedback.

2021-10-01 15:36 UTC, abdullahozdemir reviewed
İt gave an error  on my computer but I can't find the reason

2021-10-01 15:50 UTC, khicchi requested changes
it is better two write this test case from 0.
There is a lot of work done, but a kind of complicated.
It is also better to maximize the browser window.

2021-10-01 15:50 UTC, khicchi commented on src/test/java/TC1.java
> +        WebElement webDriverText = wait.until(ExpectedConditions.visibilityOfElementLocated(By.className("w3-button w3-blue")));
this webDriverText is never used. we can remove this.

2021-10-01 15:50 UTC, khicchi commented on src/test/java/TC1.java
> +        WebDriverWait wait = new WebDriverWait(driver, 60);
this wait is useless. because of this wait, after 60 seconds the code throws TimeoutException.
no need to use this line.

2021-10-01 15:50 UTC, khicchi commented on src/test/java/TC1.java
> +        writeRandomNumber.sendKeys(RandomNumber.getText());
in this test case we do not need to write the generated number.
test case mission is: generating 5 numbers and checking whether all of them are unique among others.

2021-10-01 20:10 UTC, orhanharman requested changes
Changes are requested

2021-10-01 20:10 UTC, orhanharman commented on src/test/java/TC1.java
> +
Here is unnecessary

2021-10-01 20:12 UTC, orhanharman commented
I am not sure if I am doing the correct action but I am closing the pull request

2021-10-05 13:15 UTC, abdullahozdemir reviewed
I think it is an excellent addition @ismetgunes

2021-10-06 06:41 UTC, merged